version: '2.4'

services:
  app:
    build:
      context: ../
      dockerfile: ./docker/php-fpm/Dockerfile
    image: backend_app
    volumes:
      - ../App:/application

  webserver:
    image: 'nginx:1.17.9-alpine'
    working_dir: /application
    volumes:
      - ../App:/application
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "127.0.0.1:${NGINX_PORT}:80"

  postgresql:
    image: 'bitnami/postgresql:13.0.0'
    volumes:
      - 'postgresql_master_data:/bitnami/postgresql'
    ports:
      - '127.0.0.1:${POSTGRESQL_PORT}:5432'
    environment:
      POSTGRESQL_REPLICATION_MODE: master
      POSTGRESQL_REPLICATION_USER: repl_user
      POSTGRESQL_REPLICATION_PASSWORD: repl_pass
      POSTGRESQL_USERNAME: ${POSTGRESQL_USERNAME}
      POSTGRESQL_PASSWORD: ${POSTGRESQL_PASSWORD}
      POSTGRESQL_POSTGRES_PASSWORD: ${POSTGRESQL_POSTGRES_PASSWORD}
      POSTGRESQL_DATABASE: ${POSTGRESQL_DATABASE}
      POSTGRESQL_SYNCHRONOUS_COMMIT_MODE: "off"

  test-postgresql:
    image: 'bitnami/postgresql:13.0.0'
    ports:
      - '127.0.0.1:${TEST_POSTGRESQL_PORT}:5432'
    environment:
      POSTGRESQL_USERNAME: ${TEST_POSTGRESQL_USERNAME}
      POSTGRESQL_PASSWORD: ${TEST_POSTGRESQL_PASSWORD}
      POSTGRESQL_DATABASE: ${TEST_POSTGRESQL_DATABASE}
      POSTGRESQL_POSTGRES_PASSWORD: ${POSTGRESQL_POSTGRES_PASSWORD}
volumes:
  postgresql_master_data: